trigger:
  - main
pr: none

stages:
  ############################################################
  ### Stage to Deploy Azure Infrastructure                 ###
  ############################################################
  - stage: deployAzureInfrastructure
    displayName: 'Deploy Azure Infrastructure'
    jobs:
      ### Job to Deploy Azure Infrastructure ###
      - deployment: deployAzureInfrastructure
        displayName: 'Deploy Azure Infrastructure'
        pool:
          name: 'global-aks'
        workspace:
          clean: all
        # This is the environment in ADO where the results of this job will be displayed.
        environment: 'snappass'
        strategy:
          runOnce:
            deploy:
              steps:
                ### Task to Checkout GitHub Repository
                - checkout: self
                  #dispalyName: 'Checkout GitHub Repository'
                  fetchDepth: 2
                ### Task to Replace Terraform Variables
                - task: ReplaceTokens@6
                  displayName: Replace Terraform Variables
                  inputs:
                    targetFiles: '$(REPO_MANIFEST_FOLDER)/terraform-manifests/*.tf'
                    tokenPattern: custom
                    tokenPrefix: '<-'
                    tokenSuffix: '->'
                ### Task to Assign Resource Group Permissions
                - task: AzureCLI@2
                  displayName: 'Assign Resource Group Permissions'
                  inputs:
                    azureSubscription: '$(AZURE_SERVICE_SPN)'
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      # Fail if any command fails
                      set -e
                      if $(az group exists --name "$AZURE_RG_NAME") .eq "true"; then
                        # Get Role Assignment Status
                        RG_ROLE_ASSIGNMENT=$(az role assignment list --resource-group "$AZURE_RG_NAME" --query "[?principalId=='ec55e7d4-ae11-4c67-a7bf-ce9c0085bbd0' && roleDefinitionName=='Owner'].roleDefinitionName" -o tsv)
                        # If Resource Group permissions do not exist...
                        if [[ "$RG_ROLE_ASSIGNMENT" != "Owner" ]]; then
                          echo "Adding role assignment..."
                          AZURE_RG_ID=$(az group show --name  $AZURE_RG_NAME | jq -r  '.id')
                          az role assignment create --assignee-object-id ec55e7d4-ae11-4c67-a7bf-ce9c0085bbd0 --assignee-principal-type User --role Owner --scope $AZURE_RG_ID
                        else
                          echo "Role assignment already exists."
                        fi
                      fi
                ### Task to Run Terraform Init
                - task: TerraformTaskV4@4
                  displayName: 'Run Terrafrom Init'
                  #retryCountOnTaskFailure: 3
                  inputs:
                    provider: 'azurerm'
                    command: 'init'
                    workingDirectory: '$(System.DefaultWorkingDirectory)/$(REPO_MANIFEST_FOLDER)/terraform-manifests'
                    backendServiceArm: '$(TERRAFORM_BACKEND_SPN)'
                    backendAzureRmResourceGroupName: '$(TERRAFORM_BACKEND_RG)'
                    backendAzureRmStorageAccountName: '$(TERRAFORM_BACKEND_SA)'
                    backendAzureRmContainerName: '$(TERRAFORM_BACKEND_CONTAINER)'
                    backendAzureRmKey: '$(AZURE_PROJECT_NAME).tfstate'
                ### Task to Run Terraform Plan
                - task: TerraformTaskV4@4
                  displayName: 'Run Terrafrom Plan'
                  inputs:
                    command: 'plan'
                    workingDirectory: '$(System.DefaultWorkingDirectory)/$(REPO_MANIFEST_FOLDER)/terraform-manifests'
                    backendServiceArm: '$(TERRAFORM_BACKEND_SPN)'
                    environmentServiceNameAzureRM: '$(AZURE_SERVICE_SPN)'
                    commandOptions: '-out create-$(Build.BuildId).plan'
                ### Task to Run Terraform Apply
                - task: TerraformTaskV4@4
                  displayName: 'Run Terrafrom Apply'
                  inputs:
                    command: 'apply'
                    workingDirectory: '$(System.DefaultWorkingDirectory)/$(REPO_MANIFEST_FOLDER)/terraform-manifests'
                    backendServiceArm: '$(TERRAFORM_BACKEND_SPN)'
                    environmentServiceNameAzureRM: '$(AZURE_SERVICE_SPN)'
                    commandOptions: 'create-$(Build.BuildId).plan'
                ### Task to Assign Resource Group Permissions
                - task: AzureCLI@2
                  displayName: 'Assign Resource Group Permissions'
                  inputs:
                    azureSubscription: '$(AZURE_SERVICE_SPN)'
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      # Fail if any command fails
                      set -e
                      if $(az group exists --name "$AZURE_RG_NAME") .eq "true"; then
                        # Get Role Assignment Status
                        RG_ROLE_ASSIGNMENT=$(az role assignment list --resource-group "$AZURE_RG_NAME" --query "[?principalId=='ec55e7d4-ae11-4c67-a7bf-ce9c0085bbd0' && roleDefinitionName=='Owner'].roleDefinitionName" -o tsv)
                        # If Resource Group permissions do not exist...
                        if [[ "$RG_ROLE_ASSIGNMENT" != "Owner" ]]; then
                          echo "Adding role assignment..."
                          AZURE_RG_ID=$(az group show --name  $AZURE_RG_NAME | jq -r  '.id')
                          az role assignment create --assignee-object-id ec55e7d4-ae11-4c67-a7bf-ce9c0085bbd0 --assignee-principal-type User --role Owner --scope $AZURE_RG_ID
                        else
                          echo "Role assignment already exists."
                        fi
                      fi
